[theme]
primaryColor = "#00FF66"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#111111"
textColor = "#CCCCCC"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
